HMLR 10/23 submission file with samples and means.
reichlab/variant-nowcast-hub pull request #121
Opened 2024-10-23 15:36 UTC by trobacker

UMass HMLR model for 10/23 submission. It includes `output_type` of `sample` and `mean`.

2024-10-23 17:14 UTC, nickreich requested changes
There is a space in the filename. This should be fixed.

2024-10-23 18:19 UTC, trobacker reviewed
Removed space.

2024-10-24 00:04 UTC, IsaacMacarthur approved these changes

2024-10-24 00:13 UTC, IsaacMacarthur approved these changes

2024-10-24 03:08 UTC, nickreich approved these changes

2024-10-24 03:11 UTC, nickreich commented
Noting that I flagged the whitespace in filename issue as a bug [here](https://github.com/hubverse-org/hubValidations/issues/132).

2024-10-25 00:57 UTC, merged