Yamlfile
reichlab/variant-nowcast-hub pull request #94
Opened 2024-10-04 14:55 UTC by rogersbw

Addressing metadata file comments

2024-10-04 14:59 UTC, rogersbw commented
I imagine we'll want to workshop the methods description a bit more, but I figured this would serve for now.

2024-10-04 19:08 UTC, nickreich commented on model-metadata/UMass-HMLR.yml
> +citation: "Abousamra, E., Figgins, M., & Bedford, T. (2024). Fitness models provide accurate short-term forecasts of SARS-CoV-2 variant frequency. PLOS Computational Biology, 20(9), e1012443."
I suggest removing this as it wouldn't be quite right to use this citation as an exact citation for our model, which is similar to, but different than, their approach.

2024-10-04 19:09 UTC, nickreich commented on model-metadata/UMass-HMLR.yml
> +methods: "A Bayesian hierarchical multinomial logistic regression model for nowcasting COVID variants. Regression coefficents are modeled hierarchically across variants and locations. Model is adapte
Could we say a few ways in which it is similar to/different from their model? E.g. didn't we change the way the hierarchy was used (didn't they do it across variants where we do it across locations?).

2024-10-04 19:09 UTC, nickreich commented on model-metadata/UMass-HMLR.yml
> +methods: "A Bayesian hierarchical multinomial logistic regression model for nowcasting COVID variants. Regression coefficents are modeled hierarchically across variants and locations. Model is adapte
Maybe also, in place of the citation below, we could add a journal name here, for a bit more of a "complete" citation.

2024-10-04 19:09 UTC, nickreich requested changes
Author list looks great. I have a few suggested changes for the citation/reference part.

2024-10-04 20:27 UTC, rogersbw commented
Made the suggested edits. As far as I know, the only difference for the current model that Isaac is using is that hierarchies over variants.

2024-10-06 16:23 UTC, nickreich approved these changes

2024-10-06 16:23 UTC, merged